name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    #strategy:
     # matrix:x
      #  python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
       # python3 -m pip install --upgrade pip
        pipx install pytest

    - name: Run tests
      run: |
        cd src
        python3 -m pytest addition.py
